# Use Dockerized infrastructure
sudo: false
language: python
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "${HOME}/google-cloud-sdk/"
  - "${HOME}/kubectl/"

env:
- PATH=$PATH:${HOME}/kubectl:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
- CLUSTER_NAME=standard-cluster-1
- CLUSTER_PROJECT=gcp-home-dev
- CLUSTER_ZONE=europe-west3-a
- DEPLOYMENT_NAME=saltstack-master
- FQDN=salt.th0r.de
- IMAGE=gcr.io/gcp-home-dev/saltstack-master:661461ebdd18ce3294242d924ca97d0d7d5c3cf1
- MAX_REPLICAS=1
- MIN_REPLICAS=1
- NAMESPACE=salt
- GPG_PRIVATE_KEY=dGVzdAo=


before_install:

- openssl aes-256-cbc -K $encrypted_ffc671bd29c0_key -iv $encrypted_ffc671bd29c0_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz

install:
# Set the correct project to deploy to
# set in travis project: cluster_name, cluster_zone, cluster_project
- pip install -r pip/requirements.txt
- bash scripts/install_gcloud.sh
- gcloud --version
- gcloud components install kubectl
- kubectl version
- mkdir -p ${HOME}/k8s_descriptions

## auth k8s cluster
- gcloud auth activate-service-account --key-file saltstack_deployment_secret.json
- gcloud container clusters get-credentials ${CLUSTER_NAME} --zone ${CLUSTER_ZONE} --project ${CLUSTER_PROJECT}




script:
# Render kubernetes files
- python2 scripts/render_k8s.py
- python2 scripts/deploy_k8s.py
